### ISSUE TITLE
Don't get in the habit of putting tokens in github, even testing ones

### ISSUE THREAD

**Issue by cvvs** [nick-smith8/BuffBusTracker#3]
I've found a lot of passwords on github which gave me access to peoples personal gmail and other things. I recommend you get in the habit of never checking in tokens, even if they're test tokens.

**Comment by nick-smith8** [comment]
Hey Chad!  Thx for catching that, I just took them out and that is something that I should be watching for in the future. Also, if you want to check out the app that calls this api you can search "Cu Bus Tracker" in either store!  I have some more questions about making this code better if you have time to answer them.

**Comment by cvvs** [comment]
Hey Nick,  if I don't have time, I'll make time! :)
